# Generated by Django 4.2 on 2023-04-25 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=355)),
                ('phonenumber', models.IntegerField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('fee', models.IntegerField(max_length=20)),
                ('condition', models.CharField(max_length=20)),
            ],
        ),
    ]
