# Generated by Django 4.2 on 2023-04-27 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_user2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user2',
            name='email',
            field=models.EmailField(max_length=200),
        ),
    ]
